### ISSUE TITLE
using `ledger-app-builder:latest` with `rustc 1.75.0-nightly (0f44eb32f 2023-11-09)` crashes a nanos app 

### ISSUE THREAD

**Issue by dj8yfo** [LedgerHQ/ledger-device-rust-sdk#122]
Latest image crashes a nanos app pretty reliably, both physically and in Speculos.
It has been mentioned in [comment](https://github.com/LedgerHQ/ledger-app-builder/pull/99#issuecomment-1898880685), that using latest image for nanos depends on fix in `fix/multifield_stack`  in `ledger-device-rust-sdk`. 

Can confirm that reverting to an older
```bash
ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder     <none>    3de8a37d424f   12 days ago    4.45GB
```
image doesn't have this problem with crashes in the identical app.

**Comment by dj8yfo** [comment]
i have great trouble understanding the exact reason of crashes, and also have trouble with coming up with a minimal reproducible example, but can confirm, that adding

```toml
[patch.crates-io]
ledger_device_sdk = { git = "https://github.com/LedgerHQ/ledger-device-rust-sdk", branch="fix/multifield_stack"}
ledger_secure_sdk_sys = { git = "https://github.com/LedgerHQ/ledger-device-rust-sdk", branch="fix/multifield_stack" }
```
resolves the crashes encountered on nanos, and also `MultiFieldReview` works fine in a case, where previously (on non-patch version) it truncated supplied input fields.
